//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiJunKaiOAMis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public System.Guid UserID { get; set; }
        public string RealName { get; set; }
        public string Sex { get; set; }
        public string MTel { get; set; }
        public string EMail { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<System.DateTime> EmployDate { get; set; }
        public string State { get; set; }
    
        public virtual Dep Dep { get; set; }
    }
}
