//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiJunKaiOAMis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public System.Guid UserID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string MTel { get; set; }
        public string QQ { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.Guid> CurClassId { get; set; }
    
        public virtual Classes Classes { get; set; }
    }
}
